version: '3.7'

services:
  jupyterhub:
    container_name: 'jupyterhub'
    build:
      context: .
      dockerfile: docker/jupyterhub.Dockerfile
    environment:
      - JUPYTERHUB_IP
      - JUPYTERHUB_PORT_INTERNAL
      - JUPYTERHUB_DATA
      - ADMIN_USERS
      - OAUTH_CALLBACK_URL
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
    volumes:
      - jupyterhub-data:/data
      - jupyterhub-users:/home
    networks:
      - jupyterhub-network
    restart: always

  proxy:
    container_name: 'proxy'
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    depends_on:
      - jupyterhub
    ports:
      - "${JUPYTERHUB_PORT_EXTERNAL}:80"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - PROXY_TARGET_PORT=${JUPYHUB_PORT_INTERNAL}
      - JUPYTERHUB_DOMAIN=hub-analytics.blitzun.com
      - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    networks:
      - jupyterhub-network
    restart: always

  certbot:
    image: certbot/certbot
    container_name: 'certbot'
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --agree-tos --no-eff-email --staging -d hub-analytics.blitzun.com
    networks:
      - jupyterhub-network

volumes:
  jupyterhub-data:
  jupyterhub-users:

networks:
  jupyterhub-network:
    name: jupyterhub-network